---
name: 'JavaScript Lockfile Check'
description: 'Check for and enforce the correct lockfile for your JS project.'
icon: 'lock'
color: 'yellow'
inputs:
  package-manager:
    description: 'The package manager you use'
    required: true
    default: 'npm'
outputs:
  lockfile-check-result:
    description: 'The results of the check; can be `success` or `failure`.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.package-manager }}
