---
on: [push]
name: Linting & Checks
jobs:
  lint:
    name: Lint project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Lint Dockerfile
        uses: docker://replicated/dockerfilelint
        with:
          args: Dockerfile

      - name: ShellCheck
        run: shellcheck entrypoint.sh
