---
on: [push]
name: Linting & Checks
jobs:
  lint:
    name: Lint project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0

      - name: Lint Dockerfile
        uses: docker://replicated/dockerfilelint
        with:
          args: Dockerfile

      - name: ShellCheck
        run: shellcheck entrypoint.sh

      - name: YAMLlint
        uses: ibiqlik/action-yamllint@master
        with:
          config_file: .yamllint.yml
